app/Http/routes.php
<?php

//Route::auth();
//Authentication Routes...
Route::get('login', 'Auth\AuthController@showLoginForm');
Route::post('login', 'Auth\AuthController@login');
Route::get('logout', 'Auth\AuthController@logout');

//Password Reset Routes...
Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
Route::post('password/reset', 'Auth\PasswordController@reset');

// Admin route group.
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function() {
    Route::get('', ['as' => 'admin.dashboard', 'uses' => 'Admin\AdminController@dashboard']);

    // Category CRUD.
    Route::resource('category', 'Admin\CategoryController', [
        'except' => ['show', 'destroy'],
        'parameters' => ['category' => 'id']
    ]);
    Route::get('category/{id}', ['as' => 'admin.category.destroy', 'uses' => 'Admin\CategoryController@destroy']);

    // Content CRUD.
    Route::resource('content', 'Admin\ContentController', [
        'except' => ['show', 'destroy'],
        'parameters' => ['content' => 'id']
    ]);
    Route::get('content/{id}', ['as' => 'admin.content.destroy', 'uses' => 'Admin\ContentController@destroy']);

    // Gallery CRUD
    Route::group(['prefix' => 'content/{content_id}/gallery', 'as' => 'admin.content.gallery.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'Admin\ImageController@index']);
        Route::post('store', ['as' => 'store', 'uses' => 'Admin\ImageController@store']);
        Route::post('update/{id}', ['as' => 'update', 'uses' => 'Admin\ImageController@update']);
        Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'Admin\ImageController@destroy']);
    });

    // Banner CRUD
    Route::group(['prefix' => 'content/{content_id}/banner', 'as' => 'admin.content.banner.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'Admin\BannerController@index']);
        Route::post('store', ['as' => 'store', 'uses' => 'Admin\BannerController@store']);
        Route::get('destroy', ['as' => 'destroy', 'uses' => 'Admin\BannerController@destroy']);
    });

    // Team CRUD.
    Route::resource('team', 'Admin\TeamController', [
        'except' => ['show', 'destroy'],
        'parameters' => ['team' => 'id']
    ]);
    Route::get('team/{id}', ['as' => 'admin.team.destroy', 'uses' => 'Admin\TeamController@destroy']);
    Route::post('updateAvatar/{id}', ['as' => 'admin.team.updateAvatar', 'uses' => 'Admin\TeamController@updateAvatar']);

    // Tournament CRUD
    Route::resource('tournament', 'Admin\TournamentController', [
        'except' => ['show', 'destroy'],
        'parameters' => ['tournament' => 'id']
    ]);
    Route::get('tournament/{id}', ['as' => 'admin.tournament.destroy', 'uses' => 'Admin\TournamentController@destroy']);
    Route::get('tournament/{id}/team', ['as' => 'admin.tournament.team', 'uses' => 'Admin\TournamentController@teamList']);
    Route::post('tournament/{id}/team/store', ['as' => 'admin.tournament.team.store', 'uses' => 'Admin\TournamentController@storeTeam']);
    Route::get('tournament/{id}/team/destroy/{team_id}', ['as' => 'admin.tournament.team.destroy', 'uses' => 'Admin\TournamentController@destroyTeam']);

    // Team CRUD.
    Route::resource('player', 'Admin\PlayerController', [
        'except' => ['show', 'destroy'],
        'parameters' => ['player' => 'id']
    ]);
    Route::get('player/{id}', ['as' => 'admin.player.destroy', 'uses' => 'Admin\PlayerController@destroy']);
});

// Site route group.
Route::group(['prefix' => '/', 'as' => 'site.', 'middleware' => 'web'], function() {
    Route::get('', ['as' => 'home', 'uses' => 'Site\SiteController@home']);

    Route::group(['prefix' => 'europashield2017', 'as' => 'europashield.'], function () {
        Route::get('', ['as' => 'home','uses' => 'Site\EuropaShieldController@home']);
        Route::get('content/{category_id}/{category}', ['as' => 'content.list', 'uses' => 'Site\EuropaShieldController@contentList']);
        Route::get('content/{category_id}/{category}/{slug}', ['as' => 'content.show', 'uses' => 'Site\EuropaShieldController@show']);
        Route::get('schedule', ['as' => 'schedule', 'uses' => 'Site\EuropaShieldController@schedule']);
        Route::get('standings', ['as' => 'standings', 'uses' => 'Site\EuropaShieldController@standings']);
    });
});

app/Models/Content.php
<?php

namespace NCBenfica\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Content extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $fillable = [
    	'title',
    	'slug',
        'banner',
    	'summary',
    	'body',
    	'category_id'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    public function image()
    {
        return $this->hasMany(Image::class, 'content_id', 'id');
    }

    public function file()
    {
        return $this->hasMany(File::class, 'content_id', 'id');
    }
}

app/Http/Controllers/Admin/ContentController.php
<?php

namespace NCBenfica\Http\Controllers\Admin;

use Illuminate\Http\Request;

use Illuminate\Support\Str;
use NCBenfica\Http\Requests;
use NCBenfica\Http\Controllers\Controller;
use NCBenfica\Models\Category;
use NCBenfica\Models\Content;

class ContentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $page_title = 'Conteúdos';
        $page_description = 'Lista de todos os conteúdos';
        $breadcrumb = array(['name' => 'Conteúdos']);

        $contents = Content::with('category')->latest()->paginate(15);

        return view('admin.content.index', compact('contents', 'page_title', 'page_description', 'breadcrumb'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $page_title = 'Conteúdos';
        $page_description = 'Preencha o formulário abaixo para criar um novo conteúdo';
        $breadcrumb = array(['name' => 'Conteúdos', 'link' => route('admin.content.index')], ['name' => 'Novo']);

        $categories = Category::lists('name', 'id');

        return view('admin.content.create', compact('categories', 'page_title', 'page_description', 'breadcrumb'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request['category_id'] = (empty($request['category_id']) ? null : $request['category_id']);
        $request['slug'] = Str::slug($request['title']);

        $content = Content::create($request->all());

        return redirect()->route('admin.content.edit', $content->id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $content = Content::findOrFail($id);
        $categories = Category::lists('name', 'id');

        $page_title = 'Conteúdo';
        $page_description = "Editar conteúdo: {$content->title}";
        $breadcrumb = array(['name' => 'Conteúdos', 'link' => route('admin.content.index')], ['name' => 'Editar']);

        return view('admin.content.edit', compact('content', 'categories', 'page_title', 'page_description', 'breadcrumb'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request['category_id'] = (empty($request['category_id']) ? null : $request['category_id']);
        $request['slug'] = Str::slug($request['title']);

        Content::findOrFail($id)->update($request->all());

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Content::find($id)->delete();

        return redirect()->back();
    }
}

resources/views/admin/content/_form.blade.php
<div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group has-feedback">
        {!! Form::label('category_id', 'Categoria') !!}
        <i class="fa fa-asterisk pull-right text-red" data-toggle="tooltip" title="Campo obrigatório"></i>
        {!! Form::select('category_id', $categories, null, ['placeholder' => 'Selecione...','class' => 'form-control']) !!}
        <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
        <div class="help-block with-errors"></div>
    </div>
</div>

<div class="col-xs-12 col-sm-12 col-md-6">
    <div class="form-group has-feedback">
        <i class="fa fa-asterisk pull-right text-red" data-toggle="tooltip" title="Campo obrigatório"></i>
        {!! Form::label('title', 'Título do Conteúdo') !!}
        {!! Form::text('title', null, ['class' => 'form-control', 'required']) !!}
        <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
        <div class="help-block with-errors"></div>
    </div>
</div>

@if(!empty($content))
    <div class="col-xs-12 col-sm-12 col-md-3">
        <div class="form-group has-feedback">
            {!! Form::label('created_at', 'Data do Conteúdo') !!}
            {!! Form::text('created_at', Carbon\Carbon::parse($content->created_at)->format('d/m/Y H:i') , ['class' => 'form-control datepicker datetime', 'disabled']) !!}
            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
            <div class="help-block with-errors"></div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-3">
        <div class="form-group has-feedback">
            {!! Form::label('updated_at', 'Última Atualização') !!}
            {!! Form::text('updated_at', Carbon\Carbon::parse($content->updated_at)->format('d/m/Y H:i'), ['class' => 'form-control datepicker datetime', 'disabled']) !!}
            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
            <div class="help-block with-errors"></div>
        </div>
    </div>
@endif

<div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group has-feedback">
        {!! Form::label('summary', 'Resumo do Conteúdo') !!}
        {!! Form::textarea('summary', null, ['class' => 'form-control ckeditor', 'id' => 'summary']) !!}
        <div class="help-block with-errors"></div>
    </div>
</div>

<div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group has-feedback">
        {!! Form::label('body', 'Texto do Conteúdo') !!}
        {!! Form::textarea('body', null, ['class' => 'form-control ckeditor', 'id' => 'description']) !!}
        <div class="help-block with-errors"></div>
    </div>
</div>

@push('scripts')
<script src="{{ asset('/js/ckeditor/ckeditor.js') }}"></script>
<script>
    CKEDITOR.replace('summary',
        {
            customConfig : 'config-limited.js',
            toolbarGroups: [
                {"name":"basicstyles","groups":["basicstyles"]},
                {"name":"links","groups":["links"]},
                {"name":"paragraph","groups":["align"]},
            ],
            removeButtons: 'Strike,Subscript,Superscript,Anchor,Styles,Specialchar'
        }
    );

    CKEDITOR.replace('description',
        {
            filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
            filebrowserBrowseUrl: '/laravel-filemanager?type=Files',

            customConfig : 'config-default.js',
            toolbarGroups: [
                {"name":"document","groups":["mode"]},
                {"name":"basicstyles","groups":["basicstyles"]},
                {"name":"links","groups":["links"]},
                {"name":"paragraph","groups":["list","blocks","align"]},
                {"name":"insert","groups":["insert"]},
                {"name":"styles","groups":["styles"]},
            ],
            removeButtons: 'Strike,Subscript,Superscript,Anchor,Styles,Specialchar'
        }
    );
</script>

@endpush

resources/views/admin/content/create.blade.php
@extends('admin.layout.admin_template')

@section('content')
    <div class='row'>
        <div class='col-xs-12'>
            <div class="box box-danger">
                <div class="box-header with-border">
                    <div class="col-xs-6 col-xs-offset-6 col-sm-4 col-sm-offset-8 col-md-3 col-md-offset-9 col-lg-2 col-lg-offset-10">
                        <a href="{{ route('admin.content.index') }}" class="btn btn-block btn-primary">
                            <i class="fa fa-reply"></i>&nbsp;
                            Voltar
                        </a>
                    </div>
                </div>

                {!! Form::open(['route' => 'admin.content.store', 'data-toggle' => 'validator']) !!}
                <div class="box-body">
                    <div class="nav-tabs-custom clearfix">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="javascript:void(0);">Dados do Conteúdo</a></li>
                            <li class="disabled"><a href="javascript:void(0);">Banner do Conteúdo</a></li>
                            <li class="disabled"><a href="javascript:void(0);">Galeria de Imagens</a></li>
                            {{--<li class="disabled"><a href="javascript:void(0);">Ficheiros</a></li>--}}
                        </ul>

                        <div class="tab-content">
                            <div class="tab-pane active clearfix">
                                <div class="col-xs-12">
                                    <div class="callout callout-info">
                                        <p>Preencha o formulário e clique em adicionar para habilitar as abas</p>
                                    </div>
                                </div>

                                @include('admin.content._form')
                            </div>
                        </div>
                    </div>
                </div>

                <div class="box-footer">
                    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4 row-btn">
                        <a href="{{ route('admin.content.index') }}" class="btn btn-block btn-danger btn-lg">
                            <i class="fa fa-times"></i>&nbsp;
                            Cancelar
                        </a>
                    </div>

                    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4 row-btn col-xs-offset-0 col-sm-offset-0 col-md-offset-4 col-lg-offset-4">
                        <button type="submit" class="btn btn-block bg-olive btn-lg">
                            <i class="fa fa-floppy-o"></i>&nbsp;
                            Adicionar
                        </button>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/admin/content/edit.blade.php
@extends('admin.layout.admin_template')

@section('content')
    <div class='row'>
        <div class='col-xs-12'>
            <div class="box box-danger">
                <div class="box-header with-border">
                    <div class="col-xs-6 col-xs-offset-6 col-sm-4 col-sm-offset-8 col-md-3 col-md-offset-9 col-lg-2 col-lg-offset-10">
                        <a href="{{ route('admin.content.index') }}" class="btn btn-block btn-primary">
                            <i class="fa fa-reply"></i>&nbsp;
                            Voltar
                        </a>
                    </div>
                </div>

                {!! Form::model($content, ['route' => ['admin.content.update', $content->id], 'data-toggle' => 'validator', 'method' => 'put']) !!}
                <div class="box-body">
                    <div class="nav-tabs-custom clearfix">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="javascript:void(0);">Dados do Conteúdo</a></li>
                            <li><a href="{{ route('admin.content.banner.index', $content->id) }}">Banner do Conteúdo</a></li>
                            <li><a href="{{ route('admin.content.gallery.index', $content->id) }}">Galeria de Imagens</a></li>
                            {{--<li><a href="{{ route('admin.content.files.index', $content->id) }}">Ficheiros</a></li>--}}
                        </ul>

                        <div class="tab-content">
                            <div class="tab-pane active clearfix">
                                @include('admin.content._form')
                            </div>
                        </div>
                    </div>
                </div>

                <div class="box-footer">
                    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4 row-btn">
                        <a href="{{ route('admin.content.index') }}" class="btn btn-block btn-danger btn-lg">
                            <i class="fa fa-times"></i>&nbsp;
                            Cancelar
                        </a>
                    </div>

                    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4 row-btn col-xs-offset-0 col-sm-offset-0 col-md-offset-4 col-lg-offset-4">
                        <button type="submit" class="btn btn-block bg-olive btn-lg">
                            <i class="fa fa-floppy-o"></i>&nbsp;
                            Gravar
                        </button>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/admin/content/index.blade.php
@extends('admin.layout.admin_template')

@section('content')
    <div class='row'>
        <div class='col-xs-12'>
            <div class="box box-danger">
                <div class="box-header">
                    <div class="col-xs-6 col-xs-offset-6 col-sm-4 col-sm-offset-8 col-md-3 col-md-offset-9 col-lg-2 col-lg-offset-10">
                        <a href="{{ route('admin.content.create') }}" class="btn btn-block btn-info">
                            <i class="fa fa-plus-circle"></i>
                            Criar novo
                        </a>
                    </div>
                </div>

                <div class="box-body">
                    <div class="table-list table-responsive">
                        <div class='col-xs-12'>
                            @if (count($contents) > 0)
                                <table class="table table-bordered table-striped table-hover" id="users-table">
                                    <thead>
                                    <tr>
                                        <th>Título</th>
                                        <th>Categoria</th>
                                        <th>Ações</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach ($contents as $content)
                                        <tr>
                                            <td>{{ $content->title }}</td>
                                            <td>{{ $content->category->name or null }}</td>
                                            <td>
                                                <div class="btn-group">
                                                    <button type="button" class="btn bg-navy dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                                        Ações <span class="caret"></span>
                                                    </button>
                                                    <ul class="dropdown-menu" role="menu" style="min-width: initial;">
                                                        <li>
                                                            <a href="{{route('admin.content.edit', ['id' => $content->id])}}">Editar</a>
                                                        </li>
                                                        <li>
                                                            <a href="{{route('admin.content.destroy', ['id' => $content->id])}}">Apagar</a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th>Título</th>
                                        <th>Categoria</th>
                                        <th>Ações</th>
                                    </tr>
                                    </tfoot>
                                </table>

                                <div class="alert alert-info">
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-6">
                                            A listar {{ $contents->count() }} de {{ $contents->total() }} conteúdos
                                        </div>

                                        <div class="col-xs-12  col-sm-6 text-right">
                                            Página {{ $contents->currentPage() }} de {{ $contents->lastPage() }}
                                        </div>
                                    </div>
                                </div>

                                <div class="text-center">
                                    {{ $contents->render() }}
                                </div>
                            @else
                                <div class="alert alert-danger">
                                    <i class="fa fa-warning"></i>
                                    Nenhum conteúdo foi encontrado.
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection