app/Http/routes.php
<?php

//Route::auth();
//Authentication Routes...
Route::get('login', 'Auth\AuthController@showLoginForm');
Route::post('login', 'Auth\AuthController@login');
Route::get('logout', 'Auth\AuthController@logout');

//Password Reset Routes...
Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
Route::post('password/reset', 'Auth\PasswordController@reset');

// Admin route group.
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function() {
    Route::get('', ['as' => 'admin.dashboard', 'uses' => 'Admin\AdminController@dashboard']);

    // Category CRUD.
    Route::resource('category', 'Admin\CategoryController', [
        'except' => ['show', 'destroy'],
        'parameters' => ['category' => 'id']
    ]);
    Route::get('category/{id}', ['as' => 'admin.category.destroy', 'uses' => 'Admin\CategoryController@destroy']);

    // Content CRUD.
    Route::resource('content', 'Admin\ContentController', [
        'except' => ['show', 'destroy'],
        'parameters' => ['content' => 'id']
    ]);
    Route::get('content/{id}', ['as' => 'admin.content.destroy', 'uses' => 'Admin\ContentController@destroy']);

    // Gallery CRUD
    Route::group(['prefix' => 'content/{content_id}/gallery', 'as' => 'admin.content.gallery.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'Admin\ImageController@index']);
        Route::post('store', ['as' => 'store', 'uses' => 'Admin\ImageController@store']);
        Route::post('update/{id}', ['as' => 'update', 'uses' => 'Admin\ImageController@update']);
        Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'Admin\ImageController@destroy']);
    });

    // Banner CRUD
    Route::group(['prefix' => 'content/{content_id}/banner', 'as' => 'admin.content.banner.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'Admin\BannerController@index']);
        Route::post('store', ['as' => 'store', 'uses' => 'Admin\BannerController@store']);
        Route::get('destroy', ['as' => 'destroy', 'uses' => 'Admin\BannerController@destroy']);
    });

    // Team CRUD.
    Route::resource('team', 'Admin\TeamController', [
        'except' => ['show', 'destroy'],
        'parameters' => ['team' => 'id']
    ]);
    Route::get('team/{id}', ['as' => 'admin.team.destroy', 'uses' => 'Admin\TeamController@destroy']);
    Route::post('updateAvatar/{id}', ['as' => 'admin.team.updateAvatar', 'uses' => 'Admin\TeamController@updateAvatar']);

    // Tournament CRUD
    Route::resource('tournament', 'Admin\TournamentController', [
        'except' => ['show', 'destroy'],
        'parameters' => ['tournament' => 'id']
    ]);
    Route::get('tournament/{id}', ['as' => 'admin.tournament.destroy', 'uses' => 'Admin\TournamentController@destroy']);
    Route::get('tournament/{id}/team', ['as' => 'admin.tournament.team', 'uses' => 'Admin\TournamentController@teamList']);
    Route::post('tournament/{id}/team/store', ['as' => 'admin.tournament.team.store', 'uses' => 'Admin\TournamentController@storeTeam']);
    Route::get('tournament/{id}/team/destroy/{team_id}', ['as' => 'admin.tournament.team.destroy', 'uses' => 'Admin\TournamentController@destroyTeam']);

    // Team CRUD.
    Route::resource('player', 'Admin\PlayerController', [
        'except' => ['show', 'destroy'],
        'parameters' => ['player' => 'id']
    ]);
    Route::get('player/{id}', ['as' => 'admin.player.destroy', 'uses' => 'Admin\PlayerController@destroy']);
});

// Site route group.
Route::group(['prefix' => '/', 'as' => 'site.', 'middleware' => 'web'], function() {
    Route::get('', ['as' => 'home', 'uses' => 'Site\SiteController@home']);

    Route::group(['prefix' => 'europashield2017', 'as' => 'europashield.'], function () {
        Route::get('', ['as' => 'home','uses' => 'Site\EuropaShieldController@home']);
        Route::get('content/{category_id}/{category}', ['as' => 'content.list', 'uses' => 'Site\EuropaShieldController@contentList']);
        Route::get('content/{category_id}/{category}/{slug}', ['as' => 'content.show', 'uses' => 'Site\EuropaShieldController@show']);
        Route::get('schedule', ['as' => 'schedule', 'uses' => 'Site\EuropaShieldController@schedule']);
        Route::get('standings', ['as' => 'standings', 'uses' => 'Site\EuropaShieldController@standings']);
    });
});

app/Http/Controllers/HomeController.php
<?php

namespace NCBenfica\Http\Controllers;

use NCBenfica\Http\Requests;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/Site/EuropaShieldController.php
<?php

namespace NCBenfica\Http\Controllers\Site;

use Illuminate\Http\Request;

use Illuminate\Support\Facades\DB;
use NCBenfica\Http\Requests;
use NCBenfica\Http\Controllers\Controller;
use NCBenfica\Models\Category;
use NCBenfica\Models\Content;
use NCBenfica\Models\Image;
use NCBenfica\Models\Team;

class EuropaShieldController extends Controller
{
    public function home()
    {
        $categories = Category::where('category_id', '=', 1)->get();

        $news = Content::whereHas('category', function ($query) {
            $query->where('category_id', '=', 1);
        })->latest()->take(10)->get();

        $group_a = DB::table('team_tournament')
            ->join('teams', 'teams.id', '=', 'team_tournament.team_id')
            ->orderBy('points', 'desc')
            ->where('tournament_id', '=', 6)
            ->get();

        $group_b = DB::table('team_tournament')
            ->join('teams', 'teams.id', '=', 'team_tournament.team_id')
            ->orderBy('points', 'desc')
            ->where('tournament_id', '=', 4)
            ->get();

        return view('site.europashield.home.main', compact('categories', 'group_a', 'group_b', 'news'));
    }

    public function contentList($category_id, $category)
    {
        $categories = Category::where('category_id', '=', 1)->get();
        $category = Category::findOrFail($category_id);

        $news = Content::where('category_id', '=', $category_id)->latest()->simplePaginate(8);

        $group_a = DB::table('team_tournament')
            ->join('teams', 'teams.id', '=', 'team_tournament.team_id')
            ->orderBy('points', 'desc')
            ->where('tournament_id', '=', 6)
            ->get();

        $group_b = DB::table('team_tournament')
            ->join('teams', 'teams.id', '=', 'team_tournament.team_id')
            ->orderBy('points', 'desc')
            ->where('tournament_id', '=', 4)
            ->get();

        return view('site.europashield.news.main', compact('categories', 'category', 'group_a', 'group_b', 'news'));
    }

    public function show($category_id, $category, $slug)
    {
        $categories = Category::where('category_id', '=', 1)->get();
        $category = Category::findOrFail($category_id);

        $news = Content::where('slug', '=', $slug)->latest()->first();
        $gallery = Image::where('content_id', '=', $news->id)->latest()->get();

        $group_a = DB::table('team_tournament')
            ->join('teams', 'teams.id', '=', 'team_tournament.team_id')
            ->orderBy('points', 'desc')
            ->where('tournament_id', '=', 6)
            ->get();

        $group_b = DB::table('team_tournament')
            ->join('teams', 'teams.id', '=', 'team_tournament.team_id')
            ->orderBy('points', 'desc')
            ->where('tournament_id', '=', 4)
            ->get();

        return view('site.europashield.news.show', compact('categories', 'category', 'group_a', 'group_b', 'news', 'gallery'));
    }

    public function schedule()
    {
        $categories = Category::where('category_id', '=', 1)->get();

        $group_a = DB::table('team_tournament')
            ->join('teams', 'teams.id', '=', 'team_tournament.team_id')
            ->orderBy('points', 'desc')
            ->where('tournament_id', '=', 6)
            ->get();

        $group_b = DB::table('team_tournament')
            ->join('teams', 'teams.id', '=', 'team_tournament.team_id')
            ->orderBy('points', 'desc')
            ->where('tournament_id', '=', 4)
            ->get();

        return view('site.europashield.schedule.main', compact('categories', 'group_a', 'group_b'));
    }

    public function standings()
    {
        $categories = Category::where('category_id', '=', 1)->get();

        $group_a = DB::table('team_tournament')
            ->join('teams', 'teams.id', '=', 'team_tournament.team_id')
            ->orderBy('points', 'desc')
            ->where('tournament_id', '=', 6)
            ->get();

        $group_b = DB::table('team_tournament')
            ->join('teams', 'teams.id', '=', 'team_tournament.team_id')
            ->orderBy('points', 'desc')
            ->where('tournament_id', '=', 4)
            ->get();

        return view('site.europashield.standings.main', compact('categories', 'group_a', 'group_b'));
    }
}

resources/views/site/europashield/home/_page_heading.blade.php
<!-- Page Heading
    ================================================== -->
<div class="page-heading">
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <h1 class="page-heading__title">EUROPA SHIELD <span class="highlight">2017</span></h1>
                <ol class="page-heading__breadcrumb breadcrumb">
                    <li><a href="/">Home</a></li>
                    <li class="active">Europa Shield</li>
                </ol>
            </div>
        </div>
    </div>
</div>

resources/views/site/europashield/home/main.blade.php
@extends('site.layout.site_template')

@section('content')
@include('site.europashield.home._page_heading')

<!-- Content
    ================================================== -->
<div class="site-content">
    <div class="container">
        <div class="row">
            <!-- Posts -->
            <div class="col-md-9 col-md-push-3">
                <!-- Featured News -->
                @include('site.europashield._partials._tgoo_banner')
                <div class="card card--clean">
                    <header class="card__header card__header--has-filter">
                        <h4>Recent News</h4>
                    </header>
                </div>
                <!-- Featured News / End -->
                <div class="posts posts--cards post-grid post-grid--masonry row">
                    @foreach($news as $n)
                        <div class="post-grid__item col-sm-6">
                            <div class="posts__item posts__item--card posts__item--category-1 card">
                                <figure class="posts__thumb">
                                    <div class="posts__cat">
                                        <span class="label posts__cat-label">{{ $n->category->name or null }}</span>
                                    </div>
                                    @if(!empty($n->banner))
                                    <a href="{{ route('site.europashield.content.show', [$n->category_id, $n->category->slug, $n->slug]) }}">
                                        <img src="{{ asset("/uploads/cms/content/{$n->id}/banner/{$n->banner}") }}" alt="Banner" />
                                    </a>
                                    @endif
                                </figure>
                                <div class="posts__inner card__content">
                                    <a href="{{ route('site.europashield.content.show', [$n->category_id, $n->category->slug, $n->slug]) }}" class="posts__cta"></a>
                                    <time datetime="2016-08-23" class="posts__date">{{ Carbon\Carbon::parse($n->created_at)->diffForHumans() }}</time>
                                    <h6 class="posts__title">
                                        <a href="{{ route('site.europashield.content.show', [$n->category_id, $n->category->slug, $n->slug]) }}">
                                            {{ $n->title }}
                                        </a>
                                    </h6>
                                    <div class="posts__excerpt">
                                        {{ str_limit(strip_tags($n->body), 200) }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
            <!-- Posts / End -->
            @include('site.europashield._partials._sidebar')
        </div>
    </div>
</div>
@endsection