app/Http/routes.php
<?php

//Route::auth();
//Authentication Routes...
Route::get('login', 'Auth\AuthController@showLoginForm');
Route::post('login', 'Auth\AuthController@login');
Route::get('logout', 'Auth\AuthController@logout');

//Password Reset Routes...
Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
Route::post('password/reset', 'Auth\PasswordController@reset');

// Admin route group.
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function() {
    Route::get('', ['as' => 'admin.dashboard', 'uses' => 'Admin\AdminController@dashboard']);

    // Category CRUD.
    Route::resource('category', 'Admin\CategoryController', [
        'except' => ['show', 'destroy'],
        'parameters' => ['category' => 'id']
    ]);
    Route::get('category/{id}', ['as' => 'admin.category.destroy', 'uses' => 'Admin\CategoryController@destroy']);

    // Content CRUD.
    Route::resource('content', 'Admin\ContentController', [
        'except' => ['show', 'destroy'],
        'parameters' => ['content' => 'id']
    ]);
    Route::get('content/{id}', ['as' => 'admin.content.destroy', 'uses' => 'Admin\ContentController@destroy']);

    // Gallery CRUD
    Route::group(['prefix' => 'content/{content_id}/gallery', 'as' => 'admin.content.gallery.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'Admin\ImageController@index']);
        Route::post('store', ['as' => 'store', 'uses' => 'Admin\ImageController@store']);
        Route::post('update/{id}', ['as' => 'update', 'uses' => 'Admin\ImageController@update']);
        Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'Admin\ImageController@destroy']);
    });

    // Banner CRUD
    Route::group(['prefix' => 'content/{content_id}/banner', 'as' => 'admin.content.banner.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'Admin\BannerController@index']);
        Route::post('store', ['as' => 'store', 'uses' => 'Admin\BannerController@store']);
        Route::get('destroy', ['as' => 'destroy', 'uses' => 'Admin\BannerController@destroy']);
    });

    // Team CRUD.
    Route::resource('team', 'Admin\TeamController', [
        'except' => ['show', 'destroy'],
        'parameters' => ['team' => 'id']
    ]);
    Route::get('team/{id}', ['as' => 'admin.team.destroy', 'uses' => 'Admin\TeamController@destroy']);
    Route::post('updateAvatar/{id}', ['as' => 'admin.team.updateAvatar', 'uses' => 'Admin\TeamController@updateAvatar']);

    // Tournament CRUD
    Route::resource('tournament', 'Admin\TournamentController', [
        'except' => ['show', 'destroy'],
        'parameters' => ['tournament' => 'id']
    ]);
    Route::get('tournament/{id}', ['as' => 'admin.tournament.destroy', 'uses' => 'Admin\TournamentController@destroy']);
    Route::get('tournament/{id}/team', ['as' => 'admin.tournament.team', 'uses' => 'Admin\TournamentController@teamList']);
    Route::post('tournament/{id}/team/store', ['as' => 'admin.tournament.team.store', 'uses' => 'Admin\TournamentController@storeTeam']);
    Route::get('tournament/{id}/team/destroy/{team_id}', ['as' => 'admin.tournament.team.destroy', 'uses' => 'Admin\TournamentController@destroyTeam']);

    // Team CRUD.
    Route::resource('player', 'Admin\PlayerController', [
        'except' => ['show', 'destroy'],
        'parameters' => ['player' => 'id']
    ]);
    Route::get('player/{id}', ['as' => 'admin.player.destroy', 'uses' => 'Admin\PlayerController@destroy']);
});

// Site route group.
Route::group(['prefix' => '/', 'as' => 'site.', 'middleware' => 'web'], function() {
    Route::get('', ['as' => 'home', 'uses' => 'Site\SiteController@home']);

    Route::group(['prefix' => 'europashield2017', 'as' => 'europashield.'], function () {
        Route::get('', ['as' => 'home','uses' => 'Site\EuropaShieldController@home']);
        Route::get('content/{category_id}/{category}', ['as' => 'content.list', 'uses' => 'Site\EuropaShieldController@contentList']);
        Route::get('content/{category_id}/{category}/{slug}', ['as' => 'content.show', 'uses' => 'Site\EuropaShieldController@show']);
        Route::get('schedule', ['as' => 'schedule', 'uses' => 'Site\EuropaShieldController@schedule']);
        Route::get('standings', ['as' => 'standings', 'uses' => 'Site\EuropaShieldController@standings']);
    });
});

app/Models/Content.php
<?php

namespace NCBenfica\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Content extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $fillable = [
    	'title',
    	'slug',
        'banner',
    	'summary',
    	'body',
    	'category_id'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    public function image()
    {
        return $this->hasMany(Image::class, 'content_id', 'id');
    }

    public function file()
    {
        return $this->hasMany(File::class, 'content_id', 'id');
    }
}

app/Http/Controllers/Admin/ContentController.php
<?php

namespace NCBenfica\Http\Controllers\Admin;

use Illuminate\Http\Request;

use Illuminate\Support\Str;
use NCBenfica\Http\Requests;
use NCBenfica\Http\Controllers\Controller;
use NCBenfica\Models\Category;
use NCBenfica\Models\Content;

class ContentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $page_title = 'Conteúdos';
        $page_description = 'Lista de todos os conteúdos';
        $breadcrumb = array(['name' => 'Conteúdos']);

        $contents = Content::with('category')->latest()->paginate(15);

        return view('admin.content.index', compact('contents', 'page_title', 'page_description', 'breadcrumb'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $page_title = 'Conteúdos';
        $page_description = 'Preencha o formulário abaixo para criar um novo conteúdo';
        $breadcrumb = array(['name' => 'Conteúdos', 'link' => route('admin.content.index')], ['name' => 'Novo']);

        $categories = Category::lists('name', 'id');

        return view('admin.content.create', compact('categories', 'page_title', 'page_description', 'breadcrumb'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request['category_id'] = (empty($request['category_id']) ? null : $request['category_id']);
        $request['slug'] = Str::slug($request['title']);

        $content = Content::create($request->all());

        return redirect()->route('admin.content.edit', $content->id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $content = Content::findOrFail($id);
        $categories = Category::lists('name', 'id');

        $page_title = 'Conteúdo';
        $page_description = "Editar conteúdo: {$content->title}";
        $breadcrumb = array(['name' => 'Conteúdos', 'link' => route('admin.content.index')], ['name' => 'Editar']);

        return view('admin.content.edit', compact('content', 'categories', 'page_title', 'page_description', 'breadcrumb'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request['category_id'] = (empty($request['category_id']) ? null : $request['category_id']);
        $request['slug'] = Str::slug($request['title']);

        Content::findOrFail($id)->update($request->all());

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Content::find($id)->delete();

        return redirect()->back();
    }
}

resources/views/admin/content/gallery/_photoswipe.blade.php
<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="pswp__bg"></div>

    <div class="pswp__scroll-wrap">
        <div class="pswp__container">
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
        </div>

        <div class="pswp__ui pswp__ui--hidden">
            <div class="pswp__top-bar">
                <div class="pswp__counter"></div>
                <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
                {{--<button class="pswp__button pswp__button--share" title="Share"></button>--}}
                <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
                <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>

                <div class="pswp__preloader">
                    <div class="pswp__preloader__icn">
                        <div class="pswp__preloader__cut">
                            <div class="pswp__preloader__donut"></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                <div class="pswp__share-tooltip"></div>
            </div>

            <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button>
            <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button>

            <div class="pswp__caption">
                <div class="pswp__caption__center"></div>
            </div>
        </div>
    </div>
</div>

resources/views/admin/content/gallery/_table.blade.php
<div class="box-body">
    <div class="table-list table-responsive">
        <div class='col-xs-12'>
            @if (count($gallery) > 0)
                <table class="table table-bordered table-striped table-hover" id="gallery-table">
                    <thead>
                    <tr>
                        <th>Imagem</th>
                        <th>Label</th>
                        <th>Ações</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($gallery as $image)
                        <tr>
                            <td width="150">
                                <img class="view img-responsive img-thumbnail pointer" src="{{ asset("/uploads/cms/content/{$content_id}/gallery/thumbs/{$image->name}")}}" alt="Imagem da Galeria:" class="img-responsive">
                            </td>
                            <td data-label="{{$image->label}}" id="label{{ $image->id }}">{{$image->label}}</td>
                            <td width="130">
                                <div class="btn-group">
                                    <button type="button" class="btn bg-navy dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                        Ações <span class="caret"></span>
                                    </button>

                                    <ul class="dropdown-menu" role="menu" style="min-width: initial;">
                                        <li>
                                            <a href="#" class="edit" data-action="{{$image->id}}">Editar</a>
                                        </li>
                                        <li>
                                            <a href="{{ route('admin.content.gallery.destroy', [$content_id, $image->id]) }}">Apagar</a>
                                        </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                    <tfoot>
                    <tr>
                        <th>Imagem</th>
                        <th>Label</th>
                        <th>Ações</th>
                    </tr>
                    </tfoot>
                </table>

                <div class="photoswipe hide" id="gallery">
                    @foreach ($gallery as $image)
                        <figure>
                            <a class="thumbnail" href="{{ asset($image->path) }}" data-size="{{ $image->dimensions }}">
                                <img src="{{ asset("/uploads/cms/content/{$content_id}/gallery/thumbs/{$image->name}")}}" alt="Imagem da Galeria:" class="img-responsive">
                            </a>
                        </figure>
                    @endforeach
                </div>

                <div class="alert alert-info">
                    <div class="row">
                        <div class="col-xs-12 col-sm-6">
                            A listar {{ $gallery->count() }} de {{ $gallery->total() }} imagens
                        </div>

                        <div class="col-xs-12  col-sm-6 text-right">
                            Página {{ $gallery->currentPage() }} de {{ $gallery->lastPage() }}
                        </div>
                    </div>
                </div>

                <div class="text-center">
                    {{ $gallery->render() }}
                </div>
            @else
                <div class="alert alert-danger">
                    <i class="fa fa-warning"></i>
                    Nenhuma imagem foi encontrada.
                </div>
            @endif
        </div>
    </div>
</div>

resources/views/admin/content/gallery/index.blade.php
@extends('admin.layout.admin_template')

@section('content')
    <div class='row'>
        <div class='col-xs-12'>
            <div class="box box-danger">
                <div class="box-header">
                    <div class="col-xs-6 col-xs-offset-6 col-sm-4 col-sm-offset-8 col-md-3 col-md-offset-9 col-lg-2 col-lg-offset-10">
                        <a href="{{  route('admin.content.index') }}" class="btn btn-block btn-primary">
                            <i class="fa fa-reply"></i>&nbsp;
                            Voltar
                        </a>
                    </div>
                </div>

                <div class="box-body">
                    <div class="nav-tabs-custom">
                        <ul class="nav nav-tabs">
                            <li><a href="{{  route('admin.content.edit', $content_id) }}">Dados do Conteúdo</a></li>
                            <li><a href="{{ route('admin.content.banner.index', $content_id) }}">Banner do Conteúdo</a></li>
                            <li class="active"><a href="javascript:void(0);">Galeria de Imagens</a></li>
                            {{--<li><a href="{{  route('admin.content.files.index', $content_id) }}">Ficheiros</a></li>--}}
                        </ul>

                        <div class="tab-content">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="callout callout-info">
                                        <p>Formatos suportados: JPG, JPEG, PNG, GIF</p>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-xs-12">
                                    <form action="{{  route('admin.content.gallery.store', $content_id) }}" method="POST" class="dropzone" id="my-dropzone">
                                        <div class="dz-message" data-dz-message>
                                            <h3>Arraste as imagens ou clique para adicionar</h3>
                                        </div>
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    </form>
                                </div>
                            </div>
                        </div>

                        <hr>

                        <div class="box box-info">
                            <div class="box-header">
                                <h3 class="box-title">Galeria</h3>
                            </div>
                            @include('admin.content.gallery._table')
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @include('admin.content.gallery._photoswipe')
@endsection

@push('scripts')
<script src="{{ asset("js/photoswipe-template.js") }}" type="text/javascript"></script>
<script>
$(function() {
    $('.view').on('click', function() {
        $('#gallery figure:first-child a').click();
    });

    Dropzone.options.myDropzone = {
        autoProcessQueue: true,
        uploadMultiple: true,
        paramName: 'image',
        maxFilesize: 10,
        maxFiles: 10,
        parallelUploads: 10,
        acceptedFiles: ".jpg, .jpeg, .png, .gif",
        addRemoveLinks: true,
        init: function ()
        {
            var myDropzone = this;

//                this.on("complete", function (file) {
//                   myDropzone.removeFile(file);
//                });

            this.on("success", function() {
                window.location = window.location;
            });
        }
    };

    $(".gallery figure span").on("click", function () {
        var url = $(this).data("remove");

        $.get( url, function() {
            window.location = window.location;
        });

        return false;
    });

    $('.edit').on('click', function (e) {
        e.preventDefault();

        var id = $(this).data("action");
        var td = "#label"+id;
        var label = $(td).html();

        $('#gallery-table tbody tr td:nth-child(2)').each(function() {
            $(this).html($(this).data('label'));
        });

        $(td).html('<form><div class="input-group"><input class="change-label form-control" type="text" name="label" value="'+label+'"><span class="input-group-addon" id="basic-addon2"><a href="#"><i class="fa fa-check"></i></a></span></div><input type="hidden" name="_token" value="{{ csrf_token() }}"></form>');

        $('#gallery-table form').submit(function() {
            $('#gallery-table form a').click();
            return false;
        });

        $(td + " a").on('click', function() {
            var data = $(td + " form").serialize();
            var route = "{{  route('admin.content.gallery.update', [$content_id, 0]) }}";
            route = route.replace("0", id);

            $.post(route, data, function(){
                location.reload();
            });

            return false;
        });
    });
});
</script>
@endpush